import { jsPDF } from "jspdf";

const number = value => Number(value || 0);
export const sumMeal = meal => (meal.items || []).reduce((sum, item) => ({ calories: sum.calories + number(item.calories), protein_g: sum.protein_g + number(item.protein_g), carbs_g: sum.carbs_g + number(item.carbs_g), fat_g: sum.fat_g + number(item.fat_g) }), { calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 });
export const recalcDietTotals = meals => (meals || []).reduce((sum, meal) => { const total = sumMeal(meal); return { total_calories: sum.total_calories + total.calories, protein_g: sum.protein_g + total.protein_g, carbs_g: sum.carbs_g + total.carbs_g, fat_g: sum.fat_g + total.fat_g }; }, { total_calories: 0, protein_g: 0, carbs_g: 0, fat_g: 0 });
export const analyzeDietAdherence = (plan, logs) => {
  const meals = (plan?.meals || []).map(meal => { const related = logs.filter(log => log.meal_name === meal.name || log.meal_id === meal.id); const completed = related.filter(log => log.completed !== false).length; const planned = Math.max(related.length, 1); const percent = Math.round(completed / planned * 100); return { refeicao: meal.name, concluidas: completed, planejadas: related.length, percentualAdesao: percent, statusAdesao: percent >= 75 ? "boa" : percent >= 45 ? "média" : "baixa", justificativa: related.length ? "Baseado nos registros alimentares." : "Sem registros suficientes." }; });
  return { refeicoes: meals, adesaoMedia: meals.length ? Math.round(meals.reduce((sum, meal) => sum + meal.percentualAdesao, 0) / meals.length) : 0 };
};
export const normalizeAiDiet = (response, base) => {
  const meals = (response?.meals || base?.meals || []).map(meal => ({ ...meal, items: (meal.items || meal.foods || []).map(item => ({ food_name: item.food_name || item.name || "Alimento", quantity_g: number(item.quantity_g || item.quantity), unit: item.unit || "g", calories: number(item.calories), protein_g: number(item.protein_g || item.protein), carbs_g: number(item.carbs_g || item.carbs), fat_g: number(item.fat_g || item.fat), acao: item.acao || "manter", motivo: item.motivo || "", confiancaEquivalencia: item.confiancaEquivalencia || "baixa" })) }));
  return { ...base, name: response?.nomeNovaDieta || `${base?.name || "Dieta"} evoluída`, goal: response?.objetivo || base?.goal, meals, notes: response?.estrategiaNovaDieta || base?.notes, ...recalcDietTotals(meals) };
};
export const buildDietReport = ({ owner, currentUser, basePlan, newDiet, logs, selected, requestText, aiMeta }) => ({ usuario: { nome: owner?.name || owner?.full_name || owner?.email || "Usuário" }, personal: currentUser?.full_name || currentUser?.email, periodoAnalisado: "Histórico disponível", resumoExecutivo: aiMeta?.resumoExecutivo || "Evolução criada a partir do histórico disponível.", metricasResumo: { registros: logs.length }, analiseAdesao: analyzeDietAdherence(basePlan, logs), analisePorRefeicao: [], analisePorAlimento: [], comparativoAntigoNovo: [], macrosAntigos: recalcDietTotals(basePlan?.meals || []), macrosNovos: recalcDietTotals(newDiet?.meals || []), alimentosMantidos: [], alimentosSubstituidos: [], alimentosAdicionados: [], alimentosRemovidos: [], estrategiaNovaDieta: aiMeta?.estrategiaNovaDieta || requestText, alertas: aiMeta?.alertas || [], conclusao: "Revise periodicamente a adesão e os resultados.", proximosPassos: selected, graficos: { adesaoRefeicoes: [], macrosComparativo: [], caloriasComparativo: [], statusAlimentos: [], refeicoesStatus: [], progressoCorporal: [] } });
export const buildDietPlainReport = report => [`RELATÓRIO DE EVOLUÇÃO DE DIETA`, report.usuario.nome, report.resumoExecutivo, report.estrategiaNovaDieta].filter(Boolean).join("\n\n");
export const buildDietWhatsAppReport = report => `*Evolução de dieta — ${report.usuario.nome}*\n${report.resumoExecutivo}\n${report.conclusao}`;
export const exportDietReportPdf = (report) => { const pdf = new jsPDF(); pdf.setFontSize(16); pdf.text("Relatório de Evolução de Dieta", 14, 18); pdf.setFontSize(10); pdf.text(pdf.splitTextToSize(buildDietPlainReport(report), 180), 14, 30); pdf.save("relatorio-evolucao-dieta.pdf"); };
export const openPrintableDietReport = report => { const win = window.open("", "_blank"); win?.document.write(`<pre style="font:14px Arial;white-space:pre-wrap;padding:32px">${buildDietPlainReport(report)}</pre>`); win?.document.close(); win?.print(); };