import { jsPDF } from "jspdf";

export const normalizeEvolutionReport = ({ student, currentUser, mode, selectedPlans, generatedPlans, analyses, generatedMeta, requestText, adherence, prs }) => {
  const changes = generatedPlans.flatMap(plan => plan.exercises || []);
  return { aluno: student?.name || "Aluno", personal: currentUser?.full_name || currentUser?.email, modo: mode, periodoAnalisado: "Histórico disponível", resumoExecutivo: generatedMeta?.resumoExecutivo || "Evolução baseada nos registros disponíveis.", metricaAdesao: adherence, metricasResumo: { treinosAnalisados: selectedPlans.length, prs: prs.length, exercicios: changes.length }, cicloAnterior: selectedPlans.map(plan => plan.name).join(", "), cicloNovo: generatedMeta?.nomeNovoCiclo || generatedPlans.map(plan => plan.name).join(", "), analisePorTreino: analyses, analisePorGrupoMuscular: [], comparativoAntigoNovo: changes, cargas: changes.map(exercise => ({ exercicio: exercise.exercise_name, anterior: exercise.cargaAnterior, sugerida: exercise.cargaSugerida, confianca: exercise.confiancaCarga })), estrategiaNovoCiclo: generatedMeta?.estrategiaNovoCiclo || requestText, alertas: generatedMeta?.alertas || [], conclusao: "Acompanhe a execução e ajuste as cargas conforme a resposta individual.", graficos: { adesaoTreino: [{ nome: "Adesão", valor: adherence || 0 }], statusExercicios: [], volumeGrupoMuscular: [], alteracoesExercicios: [], cargas: [], prsPeriodo: prs } };
};
export const buildPlainTextReport = report => [`RELATÓRIO DE EVOLUÇÃO DE TREINO`, report.aluno, report.resumoExecutivo, report.estrategiaNovoCiclo, report.conclusao].filter(Boolean).join("\n\n");
export const buildWhatsAppReport = report => `*Evolução de treino — ${report.aluno}*\n${report.resumoExecutivo}\n${report.conclusao}`;
export const exportReportPdf = report => { const pdf = new jsPDF(); pdf.setFontSize(16); pdf.text("Relatório de Evolução de Treino", 14, 18); pdf.setFontSize(10); pdf.text(pdf.splitTextToSize(buildPlainTextReport(report), 180), 14, 30); pdf.save("relatorio-evolucao-treino.pdf"); };
export const openPrintableReport = report => { const win = window.open("", "_blank"); win?.document.write(`<pre style="font:14px Arial;white-space:pre-wrap;padding:32px">${buildPlainTextReport(report)}</pre>`); win?.document.close(); win?.print(); };