import React from "react";
import { Users, UserCog, DollarSign, AlertTriangle, MessageSquare, Dumbbell, Utensils, ClipboardCheck, Activity, Lock, Newspaper, Sparkles, TrendingUp, ShieldCheck } from "lucide-react";
import DashboardBase from "@/components/dashboard/DashboardBase";
import DashboardPrimaryCard from "@/components/dashboard/DashboardPrimaryCard";
import DashboardMetricScroller from "@/components/dashboard/DashboardMetricScroller";
import DashboardActionCards from "@/components/dashboard/DashboardActionCards";
import DashboardAlerts from "@/components/dashboard/DashboardAlerts";
import DashboardRecentActivity from "@/components/dashboard/DashboardRecentActivity";

export default function DashboardAdmin({ user, metrics, monthlyRevenue, recentActivity }) {
  const priority = metrics.pendingPayments > 0 ? { icon: DollarSign, eyebrow: "Prioridade financeira", title: `${metrics.pendingPayments} pagamento(s) pendente(s)`, subtitle: "Há cobranças pendentes ou atrasadas que precisam de acompanhamento.", path: "/Finance", action: "Abrir financeiro", tone: "amber" } : metrics.pendingStudents > 0 ? { icon: AlertTriangle, eyebrow: "Aprovações", title: `${metrics.pendingStudents} cadastro(s) aguardando`, subtitle: "Existem novos alunos aguardando liberação administrativa.", path: "/PendingStudents", action: "Revisar", tone: "amber" } : metrics.unreadMessages > 0 ? { icon: MessageSquare, eyebrow: "Comunicação", title: `${metrics.unreadMessages} mensagem(ns) não lida(s)`, subtitle: "Há conversas aguardando acompanhamento administrativo.", path: "/Chat", action: "Ver mensagens", tone: "cyan" } : { icon: ShieldCheck, eyebrow: "Visão administrativa", title: "Operação em dia", subtitle: "Nenhum alerta administrativo prioritário neste momento.", path: "/Notificacoes", action: "Notificações", tone: "green" };
  const summary = [
    ["Alunos ativos", metrics.activeStudents, Users, "/Students", "bg-purple-400/10 text-purple-200"], ["Personais", metrics.personals, UserCog, "/PersonalManagement", "bg-cyan-400/10 text-cyan-200"], ["Assinantes", metrics.subscribers, DollarSign, "/SubscriptionManagement", "bg-emerald-400/10 text-emerald-200"], ["Aprovações", metrics.pendingStudents, AlertTriangle, "/PendingStudents", "bg-amber-400/10 text-amber-200"], ["Mensagens", metrics.unreadMessages, MessageSquare, "/Chat", "bg-pink-400/10 text-pink-200"], ["Pagamentos", metrics.pendingPayments, DollarSign, "/Finance", "bg-orange-400/10 text-orange-200"], ["Treinos", metrics.workoutPlans, Dumbbell, "/WorkoutPlans", "bg-purple-400/10 text-purple-200"], ["Dietas", metrics.dietPlans, Utensils, "/Diet", "bg-emerald-400/10 text-emerald-200"], ["Check-ins hoje", metrics.todayCheckIns, ClipboardCheck, "/Progress", "bg-cyan-400/10 text-cyan-200"], ["Exercícios", metrics.exercises, Activity, "/ExerciseLibrary", "bg-violet-400/10 text-violet-200"], ["Cal. hormonal", metrics.activeHormonal, Lock, "/CalendarioHormonalAdmin", "bg-lime-400/10 text-lime-200"], ["Notícias", metrics.sportsNews, Newspaper, "/NewsManagement", "bg-sky-400/10 text-sky-200"], ["Relatórios IA", metrics.aiReports, Sparkles, "/Relatorios", "bg-pink-400/10 text-pink-200"], ["Evolução", metrics.progress, TrendingUp, "/Progress", "bg-amber-400/10 text-amber-200"],
  ].map(([label, value, icon, path, tone]) => ({ label, value, icon, path, tone }));
  const actions = [
    { title: "Gerenciar alunos", description: "Cadastros e vínculos", icon: Users, path: "/Students", tone: "text-purple-300 bg-purple-500/10 border-purple-400/15" },
    { title: "Gerenciar personais", description: "Equipe e acessos", icon: UserCog, path: "/PersonalManagement", tone: "text-cyan-300 bg-cyan-500/10 border-cyan-400/15" },
    { title: "Assinaturas", description: "Planos e liberações", icon: DollarSign, path: "/SubscriptionManagement", tone: "text-emerald-300 bg-emerald-500/10 border-emerald-400/15" },
  ];
  const alerts = [metrics.pendingStudents > 0 && { text: `${metrics.pendingStudents} aluno(s) aguardando aprovação`, path: "/PendingStudents" }, metrics.unreadMessages > 0 && { text: `${metrics.unreadMessages} mensagem(ns) não lida(s)`, path: "/Chat" }, metrics.pendingPayments > 0 && { text: `${metrics.pendingPayments} pagamento(s) pendente(s)`, path: "/Finance" }];
  return <DashboardBase user={user} roleLabel="Administrador"><DashboardPrimaryCard icon={priority.icon} eyebrow={priority.eyebrow} title={priority.title} subtitle={priority.subtitle} path={priority.path} actionLabel={priority.action} tone={priority.tone} /><DashboardMetricScroller title="Resumo geral" items={summary} /><DashboardActionCards title="Ações administrativas" items={actions} /><DashboardAlerts alerts={alerts} financialTotal={monthlyRevenue} limit={3} /><DashboardRecentActivity items={recentActivity} /></DashboardBase>;
}